search_and_play:
  description: Search for a media item and play it on the specified plex player.
  fields:
    entity_id:
      description: The entity to play media on
      example: media_player.plex_player
    server_name:
      description: The plex server to search
      example: my-plex-server
    show_name:
      description: Name of the tv show
      example: Rick & Morty
    pick_random:
      description: Pick a random item from the results
      example: true
    media_title:
      description: Media title
      example: Go god go
    season:
      description: Show season number
      example: 1
    episode:
      description: Season episode number
      example: 10
    media_content_type:
      description: The content type of the media
      example: movie
